### ISSUE TITLE
Google Sheets API upgrade

### ISSUE THREAD

**Issue by Dove6** [Dove6/PiKlib_patcher#1]
The automatic patcher has ceased working due to [Sheets v3 API becoming obsolete on August 2, 2021](https://cloud.google.com/blog/products/g-suite/migrate-your-apps-use-latest-sheets-api).  
It requires either switching to v4 API or using more professional storage like a database.

**Comment by fabform** [comment]
Handy to [find google sheet id](https://fabform.io/a/how-to-find-google-sheet-id)
